name: Pull Requests

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: laravel/.github/.github/workflows/pull-requests.yml@35afbfe24fc0e37e0c3ca6e7cc8bfbcb3f36dcb2 # pinned ref
